package com.example.zte.greendao;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GROUP_MEMBER".
 */
@Entity(schema = "wechat")
public class GroupMember implements Parcelable{

    @Id(autoincrement = true)
    private Long id;
    private String userId;
    private String name;
    private String portraitUri;
    private String groupId;
    private String displayName;
    private String nameSpelling;
    private String displayNameSpelling;
    private String groupName;
    private String groupNameSpelling;
    private String groupPortrait;

    @Generated
    public GroupMember() {
    }

    public GroupMember(Long id) {
        this.id = id;
    }

    @Generated
    public GroupMember(Long id, String userId, String name, String portraitUri, String groupId, String displayName, String nameSpelling, String displayNameSpelling, String groupName, String groupNameSpelling, String groupPortrait) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.groupId = groupId;
        this.displayName = displayName;
        this.nameSpelling = nameSpelling;
        this.displayNameSpelling = displayNameSpelling;
        this.groupName = groupName;
        this.groupNameSpelling = groupNameSpelling;
        this.groupPortrait = groupPortrait;
    }

    public GroupMember( String userId, String name, String portraitUri, String groupId, String displayName, String nameSpelling, String displayNameSpelling, String groupName, String groupNameSpelling, String groupPortrait) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.groupId = groupId;
        this.displayName = displayName;
        this.nameSpelling = nameSpelling;
        this.displayNameSpelling = displayNameSpelling;
        this.groupName = groupName;
        this.groupNameSpelling = groupNameSpelling;
        this.groupPortrait = groupPortrait;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getNameSpelling() {
        return nameSpelling;
    }

    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    public String getDisplayNameSpelling() {
        return displayNameSpelling;
    }

    public void setDisplayNameSpelling(String displayNameSpelling) {
        this.displayNameSpelling = displayNameSpelling;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getGroupNameSpelling() {
        return groupNameSpelling;
    }

    public void setGroupNameSpelling(String groupNameSpelling) {
        this.groupNameSpelling = groupNameSpelling;
    }

    public String getGroupPortrait() {
        return groupPortrait;
    }

    public void setGroupPortrait(String groupPortrait) {
        this.groupPortrait = groupPortrait;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.userId);
        dest.writeString(this.name);
        dest.writeString(this.portraitUri);
        dest.writeString(this.groupId);
        dest.writeString(this.displayName);
        dest.writeString(this.nameSpelling);
        dest.writeString(this.displayNameSpelling);
        dest.writeString(this.groupName);
        dest.writeString(this.groupNameSpelling);
        dest.writeString(this.groupPortrait);
    }

    protected GroupMember(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.userId = in.readString();
        this.name = in.readString();
        this.portraitUri = in.readString();
        this.groupId = in.readString();
        this.displayName = in.readString();
        this.nameSpelling = in.readString();
        this.displayNameSpelling = in.readString();
        this.groupName = in.readString();
        this.groupNameSpelling = in.readString();
        this.groupPortrait = in.readString();
    }

    public static final Creator<GroupMember> CREATOR = new Creator<GroupMember>() {
        @Override
        public GroupMember createFromParcel(Parcel source) {
            return new GroupMember(source);
        }

        @Override
        public GroupMember[] newArray(int size) {
            return new GroupMember[size];
        }
    };
}
