package com.example.zte.greendao;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "GROUPS".
 */
@Entity(schema = "wechat")
public class Groups implements Parcelable{

    @Id(autoincrement = true)
    private Long id;
    private String groupId;
    private String name;
    private String portraitUri;
    private String displayName;
    private String role;
    private String bulletin;
    private String timestamp;
    private String nameSpelling;

    @Generated
    public Groups() {
    }

    public Groups(Long id) {
        this.id = id;
    }

    @Generated
    public Groups(Long id, String groupId, String name, String portraitUri, String displayName, String role, String bulletin, String timestamp, String nameSpelling) {
        this.id = id;
        this.groupId = groupId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.role = role;
        this.bulletin = bulletin;
        this.timestamp = timestamp;
        this.nameSpelling = nameSpelling;
    }

    public Groups(String groupId, String name, String portrait, String s) {
        this.groupId = groupId;
        this.name = name;
        this.portraitUri = portrait;
        this.role = s;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getBulletin() {
        return bulletin;
    }

    public void setBulletin(String bulletin) {
        this.bulletin = bulletin;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getNameSpelling() {
        return nameSpelling;
    }

    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.groupId);
        dest.writeString(this.name);
        dest.writeString(this.portraitUri);
        dest.writeString(this.displayName);
        dest.writeString(this.role);
        dest.writeString(this.bulletin);
        dest.writeString(this.timestamp);
        dest.writeString(this.nameSpelling);
    }

    protected Groups(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.groupId = in.readString();
        this.name = in.readString();
        this.portraitUri = in.readString();
        this.displayName = in.readString();
        this.role = in.readString();
        this.bulletin = in.readString();
        this.timestamp = in.readString();
        this.nameSpelling = in.readString();
    }

    public static final Creator<Groups> CREATOR = new Creator<Groups>() {
        @Override
        public Groups createFromParcel(Parcel source) {
            return new Groups(source);
        }

        @Override
        public Groups[] newArray(int size) {
            return new Groups[size];
        }
    };
}
