package com.example.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "USER".
 */
@Entity(schema = "android")
public class user {

    @Id(autoincrement = true)
    private Long id;
    private String user_name;
    private Integer user_age;

    @Generated
    public user() {
    }

    public user(Long id) {
        this.id = id;
    }

    @Generated
    public user(Long id, String user_name, Integer user_age) {
        this.id = id;
        this.user_name = user_name;
        this.user_age = user_age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public Integer getUser_age() {
        return user_age;
    }

    public void setUser_age(Integer user_age) {
        this.user_age = user_age;
    }

}
